CREATE TABLE `posts` (
    `id` INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `title` VARCHAR(256) NOT NULL, 
    `content` TEXT NOT NULL, -- TEXT == VARCHAR(65535)
    `views` INT(11) UNSIGNED NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT NOW(),
    `updated_at` DATETIME NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP
);