CREATE TABLE `post` (
    `id` INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `title` VARCHAR(256) NOT NULL,
    `content` TEXT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT NOW(),
    `updated_at` DATETIME NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP
);